steps:
# - name: 'gcr.io/cloud-builders/docker'
  # args: [ 'build', '-t', 'gcr.io/al-ulaa-dev/ulaa-eats-core-image:$SHORT_SHA', '.' ]
# - name: 'gcr.io/cloud-builders/docker'
  # args: [ 'push', 'gcr.io/al-ulaa-dev/ulaa-eats-core-image:$SHORT_SHA']
# options:
  # logging: NONE

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: [ 'build', 'submit', '--region=us-west2',  '--tag', 'us-west2-docker.pkg.dev/al-ulaa-dev/ulaa-repo/ulaa-eats-core-image:0.0.2' ]

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image:$REVISION_ID", "."]
# - name: 'gcr.io/cloud-builders/docker'
#   args: ["push", "gcr.io/$PROJECT_ID/image:$REVISION_ID"]
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
# 	- 'set'
# 	- 'image'
# 	- 'deployment/my-deployment'
# 	- 'my-container=gcr.io/$PROJECT_ID/image:$REVISION_ID'
#   env:
# 	- 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
# 	- 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: [ 'container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/ulaa-eats-core', 'gcr.io/$PROJECT_ID/ulaa-eats-core:' ]
# Test cloud Build automation
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ulaa-eats-core:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/ulaa-eats-core:latest']
options:
  logging: CLOUD_LOGGING_ONLY